<a href="https://colab.research.google.com/github/skylarvotaw/Math311_Linear_Algebra_Projects/blob/main/Gram_Schmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import matplotlib.pyplot as plt
import numpy as np

# Let's figure out some sector operations!

In [10]:
# create a vector
v = np.array([[1],[2],[3],[4]])
v

array([[1],
       [2],
       [3],
       [4]])

In [11]:
# Add vectors to vectors:

v + v

array([[2],
       [4],
       [6],
       [8]])

In [12]:
# Scale a vector:

5*v

array([[ 5],
       [10],
       [15],
       [20]])

# Gram-Schmidt Process for four vectors

In [22]:
# Create 4 random vectors

r1 = np.array([0, 3, -3, 0])
r2 = np.array([2, 6, -2, 2])
r3 = np.array([-2, 1, -3, 0])
r4 = np.array([2, -4, -2, -4])

In [23]:
print("the first random vector is ", r1)

the first random vector is  [ 0  3 -3  0]


# Let's process the first vector

In [25]:
# Chose r1
t1 = r1
print(t1)

[ 0  3 -3  0]


In [28]:
# Normalize t1, and save it as our nice vector u1:
n1 = np.sqrt(t1.dot(t1))
print(n1)

4.242640687119285


In [32]:
# Form u1
u1 = (1/n1) * t1
u1
print("our first nice vector is u1: ", u1)

our first nice vector is u1:  [ 0.          0.70710678 -0.70710678  0.        ]


In [36]:
# Check

u1.dot(u1)

np.float64(1.0000000000000002)

In [41]:
#  Choose r2
#  Subtract off the nice basis vectors:
t2 = r2 - r2.dot(u1)   * u1
print(t2)

#  Normalize t2
n2 = np.sqrt(t2.dot(t2))
print(n2)

# Form u2
u2 = (1/n2) * t2
print(u2)

[2. 2. 2. 2.]
4.0
[0.5 0.5 0.5 0.5]


In [57]:
#Check
print("size of u2 = ", u2.dot(u2))
print("u1.u2 = ", u1.dot(u2))

size of u2 =  1.0
u1.u2 =  -3.3306690738754696e-16


In [48]:
#  Choose r3
#   Subtract off the nice basis vectors:
t3 = r3 - r3.dot(u1)   * u1   -  r3.dot(u2)  * u2
print(t3)

##  Normalize t3:
n3 = np.sqrt(t3.dot(t3))
print(n3)

##  Form u3
u3 = (1/n3) * t3
print(u3)

[-1.00000000e+00 -4.44089210e-16  1.33226763e-15  1.00000000e+00]
1.4142135623730951
[-7.07106781e-01 -3.14018492e-16  9.42055475e-16  7.07106781e-01]


In [56]:
#Check
print("size of u3 = ", u3.dot(u3))
print("u3.u1 = ", u3.dot(u1))
print("u3.u2 = ", u3.dot(u2))

size of u3 =  0.9999999999999998
u3.u1 =  -8.881784197001252e-16
u3.u2 =  6.106226635438361e-16


In [53]:
#  Choose r4
#   Subtract off the nice basis vectors:
t4 = r4 - r4.dot(u1)   * u1   -  r4.dot(u2)  * u2 - r4.dot(u3) * u3
print(t4)

##  Normalize t4:
n4 = np.sqrt(t4.dot(t4))
print(n4)

##  Form u4
u4 = (1/n4) * t4
print(u4)

[ 1. -1. -1.  1.]
2.0000000000000004
[ 0.5 -0.5 -0.5  0.5]


In [58]:
#Check
print("size of u4 = ", u4.dot(u4))
print("u4.u1 = ", u4.dot(u1))
print("u4.u2 = ", u4.dot(u2))
print("u4.u3 = ", u4.dot(u3))

size of u4 =  0.9999999999999999
u4.u1 =  -2.4424906541753444e-15
u4.u2 =  1.1657341758564144e-15
u4.u3 =  5.551115123125783e-17
